### ISSUE TITLE
miniconda installation

### ISSUE THREAD

**Issue by evans-nyang** [DataTalksClub/llm-zoomcamp#52]
Been following through with the coursework for a few weeks now, I'd like to propose the enhancement below for users who have limited storage space/ram to leverage anaconda.

 - [ ] Add bash script for easy installation of miniconda as part of initial environment configuration

**Comment by alexeygrigorev** [comment]
How would it look like?

**Comment by evans-nyang** [comment]
This is the raw file content:

```sh
#!/usr/bin/env bash

# Define Miniconda version
MINICONDA_VERSION="Miniconda3-py310_24.4.0-0-Linux-x86_64.sh"

# Download Miniconda installer
wget https://repo.anaconda.com/miniconda/$MINICONDA_VERSION -O miniconda.sh

# Make the installer executable
chmod +x miniconda.sh

# Run the installer
./miniconda.sh -b -p $HOME/miniconda

# Add Miniconda to PATH in .bashrc
echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc

# Activate the installation
source $HOME/.bashrc

# Remove the installer
rm miniconda.sh

# Update conda
conda update -y conda

# Display conda version to verify installation
conda --version
```

Save the above content into a file e.g `install_miniconda.sh`. Navigate to the directory where the file exists and execute the commands below in the terminal for miniconda installation:
```
chmod +x install_miniconda.sh
source install_miniconda.sh
```


Note: This configuration will apply for linux and wsl2 users.

**Comment by alexeygrigorev** [comment]
Sure, you can create a separate page with miniconda installation and create a link to it

**Comment by alexeygrigorev** [comment]
I'll close it for now
